# Basic Math
Without Pytorch

In [4]:
# 1.Vectors dot product
import numpy as np
a = np.array([1,2,3])
b = np.array([6,5,4])
dot = np.sum(a*b)
print("Dot Product: ", dot)

x = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([1, 1, 1])

print(x + b)

Dot Product:  28
[[2 3 4]
 [5 6 7]]


In [3]:
# 2.Matrix Multiplication
def matrix_mul(A,B):
  n,m = A.shape
  m2,p = B.shape
  assert m == m2

  C = np.zeros((n,p))

  for i in range(n):
    for j in range(p):
      for k in range(m):
        C[i][j] += A[i][k] * B[k][j]
  return C

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(matrix_mul(A, B))

[[19. 22.]
 [43. 50.]]


In [5]:
# 3.Gradient Intuition
def numerical_grad(f,x,h=1e-5):
  return (f(x+h)-f(x-h) / (2*h))
def f(x):
  return x**2
x = 3.0
print("Numerical grad:", numerical_grad(f, x))
print("True grad:", 2*x)

Numerical grad: -449987.9999449998
True grad: 6.0


In [7]:
# Linear Regression from scartch
import numpy as np
np.random.seed(0)
X = np.random.randn(100,1)
true_w = 3
truw_b = 2

y = true_w*X + truw_b + 0.1*np.random.randn(100,1)

w = np.random.randn(1)
b = np.random.randn(1)
lr = 0.1

for epoch in range(1000):
  y_pred = w * X + b # Changed B to b
  loss = np.mean((y_pred - y)**2)

  dw = 2 * np.mean((y_pred - y) * X)
  db = 2 * np.mean(y_pred - y)

  w -= lr * dw
  b -= lr * db

print("Learned w:", w)
print("Learned b:", b)


Learned w: [3.01146984]
Learned b: [2.00751531]


# Pytorch Basics
Tensor Operations

In [8]:
import torch

x = torch.tensor([[1.,2.], [3.,4.]])
print(x.shape)
print(x.dtype)
print(x.device)

y = torch.sin(x)
z = torch.matmul(x, x)
print(y)
print(z)

torch.Size([2, 2])
torch.float32
cpu
tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568]])
tensor([[ 7., 10.],
        [15., 22.]])


In [9]:
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 2*x
y.backward()
print(x.grad)

tensor(8.)


**Linear Regression In Pytorch**

In [11]:
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
lr = 0.01
for _ in range(1000):
  x = torch.randn(10)
  y = 3*x + 2
  y_pred = w*x +b
  loss = ((y_pred-y)**2).mean()

  loss.backward()
  with torch.no_grad():
    w-=lr*w.grad
    b-=lr*b.grad
  w.grad.zero_()
  b.grad.zero_()

**Neural Network**

In [12]:
import torch.nn as nn

class MyNet(nn.Module):
  def __init__(self):
    super().__init__()
    self.fc1 = nn.Linear(10,32)
    self.relu = nn.ReLU()
    self.fc2 = nn.Linear(32,1)

  def forward(self, x):
    x = self.relu(self.fc1(x))
    return self.fc2(x)

model = MyNet()
model = torch.compile(model)

x = torch.randn(32,10)
output = model(x)
print(output)

tensor([[-0.1121],
        [ 0.2224],
        [-0.3166],
        [-0.2274],
        [-0.0364],
        [ 0.0188],
        [-0.1666],
        [ 0.1353],
        [-0.5375],
        [ 0.0622],
        [-0.0167],
        [ 0.0494],
        [-0.4406],
        [-0.0846],
        [-0.0310],
        [-0.3502],
        [-0.4414],
        [ 0.0301],
        [-0.4638],
        [-0.0134],
        [-0.6026],
        [-0.3914],
        [-0.2414],
        [-0.4646],
        [ 0.0053],
        [-0.4350],
        [-0.2328],
        [-0.0283],
        [ 0.3160],
        [ 0.1191],
        [-0.1163],
        [ 0.0625]], grad_fn=<CompiledFunctionBackward>)
